In [1]:
import numpy as np
from scipy.optimize import linear_sum_assignment

In [2]:
matrix = np.array( [[5, 7, 11, 6, 7],
                    [8, 5, 5, 6, 5],
                    [6, 7, 10, 7, 3],
                    [10, 4, 8, 2, 4],])

cost_matrix = []

for row in matrix:
    cost_row = []
    for col in row:
        cost_row += [np.amax(matrix) - col]
    cost_matrix += [cost_row]

print(cost_matrix)

[[6, 4, 0, 5, 4], [3, 6, 6, 5, 6], [5, 4, 1, 4, 8], [1, 7, 3, 9, 7]]


In [3]:
drow = np.zeros((5,), dtype = int)
ncost_matrix = np.vstack((cost_matrix, drow))

print(ncost_matrix)

[[6 4 0 5 4]
 [3 6 6 5 6]
 [5 4 1 4 8]
 [1 7 3 9 7]
 [0 0 0 0 0]]


In [4]:
row_ind, col_ind = linear_sum_assignment(ncost_matrix)
opt_ass = col_ind
tp = np.vstack((matrix, drow))[row_ind, col_ind].sum()
print(opt_ass)
print('the total prpfit is %d' %tp)

[2 3 1 0 4]
the total prpfit is 34
